# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:       carlessanagustin.com
email:       ''
description: 'DevOps Passionate'
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://carlessanagustin.com' # The base hostname & protocol for your site

twitter:     'https://twitter.com/carlesanagustin'
github:      'https://github.com/carlessanagustin/'
linkedin:    'https://www.linkedin.com/in/carlessanagustin/'
youtube:     'https://www.youtube.com/playlist?list=PLF3EgRIVV_yR5JuitW2TwVe3bvYtPh7zK'

markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
